baseURL = 'https://maipolemann.github.io/coihuesur/'
languageCode = 'es-ar'
title = 'Coihue Sur'
theme = 'ananke'

[params]
background_color_class = 'bg-dark-gray'
body_classes = 'theme-corporate'
custom_css = ['custom.css']
